server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/microservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/