server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/ec_jpa_hibernate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop