server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ec_sw
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update